import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/contextApi";
import { ReactQueryProvider } from "@/ReactQueryProvider";
import { SocketProvider } from "@/utils/SocketProvider";
import ReduxProvider from "@/_App";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Roboto+Mono:wght@100..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-inter antialiased">
        <ReduxProvider>
          <SocketProvider>
            <ReactQueryProvider>
              <AuthProvider>
                {children}
                <Toaster richColors position="top-right" />
              </AuthProvider>
            </ReactQueryProvider>
          </SocketProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
